#-------------------------------
# General Site Settings

menu:
# - {name: 'Resume', url: 'assets/docs/CN_RESUME.pdf'}
# - {name: 'CV', url: 'assets/docs/cn_cv.pdf'}
- {name: 'Publications',     url: 'pubs'}

#-------------------------------
# Projects Section

projects:
- {name: 'Project One',   url: 'proj-1'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/ccnguyen'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/ccnguyenn'}
- {icon: 'envelope',  link: 'mailto:mailto:cindyn@netflix.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Cindy M. Nguyen '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
